# This is a basic workflow to help you get started with Actions

name: dramaturgo_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '50 3 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}
          
      # Instalando as dependencias  
      - run: npx playwright install-deps
      
      # Relatorio e teste
      - run: npm run make-report
             
      
      #artefatos
      - name: Upload Screenshots
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: screenshots
          path: test-results
          
      - name: Upload Videos
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: videos
          path: test-results
          
      - name: Relatorio
        uses: actions/upload-artifact@v2.2.4
        if: always()
        with:
          name: report 
          path: playwright-report
